# Generated by Django 4.2.4 on 2023-12-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appfiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documentdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("language", models.CharField(max_length=50)),
                ("weighting_algorithm", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(name="IndexedDocument",),
    ]
