# Generated by Django 4.2.4 on 2023-12-29 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appfiles", "0002_documentdata_delete_indexeddocument"),
    ]

    operations = [
        migrations.RemoveField(model_name="documentdata", name="created_at",),
    ]
